spring.application.name=UberApp

spring.datasource.url=jdbc:postgresql://ep-small-mud-a56467qm-pooler.us-east-2.aws.neon.tech:5432/uber?sslmode=require
spring.datasource.username=test_owner
spring.datasource.password=jK7EcTYegs9F
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


#spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect